version: "3.7"

# environment
x-volumes: &env-volume
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "82d7c79e7e80f650d2266a66934c323fec49a27c9225a34f45939c5d7d3c501f"

  MONGO_URL: "mongodb://root:password@db:27017/flask_blog_db?authSource=admin"
  DEBUG: "True"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayan32biswas/flask_blog:latest
    container_name: flask_blog_server
    command: "flask --app app.app run --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    environment:
      <<: *env-volume
    # env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - flask_blog-backend-tier

  db:
    image: mongo
    # restart: always
    container_name: flask_blog_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - flask_blog-db:/data/db
    networks:
      - flask_blog-backend-tier

volumes:
  flask_blog-db:
    driver: local

networks:
  flask_blog-backend-tier:
    driver: bridge
